name: Build and Publish Docker Image

on:
  workflow_dispatch:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to DockerHub
      uses: docker/login-action@v3 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Docker meta
      id: docker_meta
      uses: docker/metadata-action@v5
      with:
        images: morrin356/webodm_webapp_dev
        tags: |
          type=semver,pattern={{version}}
    - name: Build and push Docker image
      id: docker_build
      uses: docker/build-push-action@v6
      with:
        context: .
        # platforms: linux/amd64,linux/arm64
        platforms: linux/amd64
        push: true
        no-cache: true
        tags: |
          ${{ steps.docker_meta.outputs.tags }}
          morrin356/webodm_webapp_dev:latest
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
